/******************************************************************************
* File Name:   interface.h
*
* Description: This is the source code for the XMC MCU: SPI MASTER Example for
*              ModusToolbox. This file contains information about the SPI pins
*              required for the interface of SPI peripheral.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2021, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#ifndef INTERFACE_H_
#define INTERFACE_H_

#include "cybsp.h"
#include "xmc_gpio.h"

/*******************************************************************************
* Macros
*******************************************************************************/
#ifdef TARGET_KIT_XMC47_RELAX_V1

/* MOSI Pin */
#define SPIM_MOSI_PORT         XMC_GPIO_PORT0
#define SPIM_MOSI_PIN          (5U)

/* MISO Pin */
#define SPIM_MISO_PORT         XMC_GPIO_PORT0
#define SPIM_MISO_PIN          (4U)

/* Slave Select Pin */
#define SPIM_SEL0_PORT         XMC_GPIO_PORT0
#define SPIM_SEL0_PIN          (6U)

/* SPI Clock Pin */
#define SPIM_SCLKOUT_PORT      XMC_GPIO_PORT0
#define SPIM_SCLKOUT_PIN       (11U)

#endif

#ifdef TARGET_KIT_XMC14_BOOT_001

/* MOSI Pin */
#define SPIM_MOSI_PORT         XMC_GPIO_PORT1
#define SPIM_MOSI_PIN          (0U)

/* MISO Pin */
#define SPIM_MISO_PORT         XMC_GPIO_PORT2
#define SPIM_MISO_PIN          (0U)

/* Slave Select Pin */
#define SPIM_SEL0_PORT         XMC_GPIO_PORT0
#define SPIM_SEL0_PIN          (9U)

/* SPI Clock Pin */
#define SPIM_SCLKOUT_PORT      XMC_GPIO_PORT0
#define SPIM_SCLKOUT_PIN       (8U)

#endif

#endif /* INTERFACE_H */

/* [] END OF FILE */
