/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: SPI Master Example
*              for ModusToolbox. This code example shows how to transfer 3 bytes of
*              data using SPI in XMC MCU. The successful transfer of bytes is
*              indicated by the toggling of an LED.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "xmc_spi.h"
#include "interface.h"

/*******************************************************************************
* Defines
*******************************************************************************/

/* Declarations for LED toggle and SPI transmission timing */
#define TICKS_PER_SECOND       (1000u)
#define TICKS_WAIT             (1000u)

#ifdef TARGET_KIT_XMC47_RELAX_V1

/* SPI1 Channel 0 */
#define SPI_MODULE_CH0         XMC_SPI1_CH0           

/* SPI Channel Input Stage */
#define SPI_DIN_STAGE          XMC_SPI_CH_INPUT_DIN0  

/* MISO input source */
#define SPI_DIN_INPUT_SOURCE   USIC1_C0_DX0_P0_4      

/* MOSI Pin drive mode */
#define SPI_MOSI_DRV_MODE      XMC_GPIO_MODE_OUTPUT_PUSH_PULL | XMC_GPIO_MODE_OUTPUT_ALT2

/* Slave Select Pin drive mode */
#define SPI_SEL0_DRV_MODE      XMC_GPIO_MODE_OUTPUT_PUSH_PULL | XMC_GPIO_MODE_OUTPUT_ALT2

/* Clock Pin drive mode */
#define SPI_SCLKOUT_DRV_MODE   XMC_GPIO_MODE_OUTPUT_PUSH_PULL | XMC_GPIO_MODE_OUTPUT_ALT2

#endif

#ifdef TARGET_KIT_XMC14_BOOT_001

/* Defines SPI1 Channel 0 */
#define SPI_MODULE_CH0         XMC_SPI0_CH0

/* Defines SPI Channel Input Stage */
#define SPI_DIN_STAGE          XMC_SPI_CH_INPUT_DIN0 

/* Defines MISO input source */
#define SPI_DIN_INPUT_SOURCE   USIC0_C0_DX0_P2_0

/* MOSI Pin drive mode */ 
#define SPI_MOSI_DRV_MODE      XMC_GPIO_MODE_OUTPUT_PUSH_PULL | XMC_GPIO_MODE_OUTPUT_ALT7

/* Slave Select Pin drive mode */
#define SPI_SEL0_DRV_MODE      XMC_GPIO_MODE_OUTPUT_PUSH_PULL | XMC_GPIO_MODE_OUTPUT_ALT6

/* Clock Pin drive mode */
#define SPI_SCLKOUT_DRV_MODE   XMC_GPIO_MODE_OUTPUT_PUSH_PULL | XMC_GPIO_MODE_OUTPUT_ALT6

#endif

/* Declaration of array to store the message to be transmitted */
const uint8_t data[3] = {0x84, 0xF, 0x84};

/* Configuration of SPI */
XMC_SPI_CH_CONFIG_t spi_config =
{   
    /* Baud Rate Configurations */
    .baudrate = 1000000U,

    /* Defines the SPI bus mode */
    .bus_mode = XMC_SPI_CH_BUS_MODE_MASTER,     
    
    /* Defines the Polarity of the slave select signals */
    .selo_inversion = XMC_SPI_CH_SLAVE_SEL_INV_TO_MSLS,   
    
    /* Defines the Parity of the USIC channel */
    .parity_mode = XMC_USIC_CH_PARITY_MODE_NONE           
};

/*******************************************************************************
* Function Name: SysTick_Handler
********************************************************************************
* Summary:
* This is the interrupt handler function for the SysTick timer interrupt.
* It counts the time elapsed in milliseconds since the timer started.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/
void SysTick_Handler(void)
{
    /* Variables Initialization */
    uint8_t i = 0;
    static uint32_t ticks = 0;

    ticks++;
    if (ticks == TICKS_WAIT)
    {
        /* Enable the selected slave Select line 0 */
        XMC_SPI_CH_EnableSlaveSelect(SPI_MODULE_CH0, XMC_SPI_CH_SLAVE_SELECT_0);

        /* Sending 3 messages from data array */
        while(i < 3)
        {
            XMC_SPI_CH_Transmit(SPI_MODULE_CH0, data[i++], XMC_SPI_CH_MODE_STANDARD);
            while((XMC_SPI_CH_GetStatusFlag(SPI_MODULE_CH0) & XMC_SPI_CH_STATUS_FLAG_TRANSMIT_SHIFT_INDICATION) == 0U);
            XMC_SPI_CH_ClearStatusFlag(SPI_MODULE_CH0, XMC_SPI_CH_STATUS_FLAG_TRANSMIT_SHIFT_INDICATION);
        }

        /* Transfer completed successfully. Toggle the LED */
        XMC_GPIO_ToggleOutput(CYBSP_USER_LED1_PORT, CYBSP_USER_LED1_PIN);

        /* Disable Slave Select line */
        XMC_SPI_CH_DisableSlaveSelect( SPI_MODULE_CH0 );

        ticks = 0;
    }
}

/*******************************************************************************
 * Function Name: main
 ********************************************************************************
 * Summary:
 * This is the main function. It initializes the SPI interface and configures
 * SPI block for transmitting data.
 *
 * Parameters:
 *  void
 *
 * Return:
 *  int
 *
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();

    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize and Start SPI */
    XMC_SPI_CH_Init(SPI_MODULE_CH0, &spi_config);

    /* Configures different SPI Port Pins */
    XMC_GPIO_SetMode(SPIM_MOSI_PORT, SPIM_MOSI_PIN, SPI_MOSI_DRV_MODE);
    XMC_GPIO_SetMode(SPIM_SEL0_PORT, SPIM_SEL0_PIN, SPI_SEL0_DRV_MODE);
    XMC_GPIO_SetMode(SPIM_SCLKOUT_PORT, SPIM_SCLKOUT_PIN, SPI_SCLKOUT_DRV_MODE);

    /* Selects the data source for SPI input stage */
    XMC_SPI_CH_SetInputSource(SPI_MODULE_CH0, SPI_DIN_STAGE, SPI_DIN_INPUT_SOURCE);

    /* Start the SPI Channel */
    XMC_SPI_CH_Start( SPI_MODULE_CH0 );

    /* System timer configuration */
    SysTick_Config(SystemCoreClock / TICKS_PER_SECOND);

    while(1);
}

/* [] END OF FILE */
